# 开发环境配置
server:
  # 服务器的HTTP端口，默认为6868
  port: 6868
  servlet:
    # 应用的访问路径
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    org.springframework: info

# Spring配置
spring:
  application:
    name: ruoyi-beiqi-admin
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1GB
      # 设置总上传的文件大小
      max-request-size: 1GB
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static,file:${ruoyi-beiqi-admin.local-storage-path}
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  mail:
    host: mail.baicintl.com
    port: 465
    username: XXX@XX.com
    password: cti@20241030
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: mail.baicintl.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: TOKEN-SECRT
  # 令牌有效期（默认30分钟）
  expireTime: 60


# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /monitor/*,/tool/*

