# 项目相关配置
ruoyi:
  # 名称
  name: ruoyi-beiqi
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /dianyi/app/data/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

ufo:
  storage-type: 0  #存储类型 0 本地存储
  local-storage-path: /dianyi/app/data/uploadPath  #本地文件存储路径
  aliyun: #阿里云oss基本配置
    oss:
      access-key-id:
      access-key-secret:
      bucket-name:
      endpoint:
  thumb-image: #图片缩略图
    width: 150
    height: 150

#FastDFS配置
#fdfs:
#  connect-timeout: 601
#  so-timeout: 1501
#  tracker-list: localhost:22122


# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://192.168.0.243:3306/baicintl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: PASSWORD
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /DRUID-UI-STRING/*
        # 控制台管理用户名和密码
        login-username: USERNAME
        login-password: PASSWORD
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true


  # redis 配置
  redis:
    # 地址
    host: HOST
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 3



# 第三方登录，参考 https://justauth.wiki/guide/oauth
just-auth:
  gitee:
    clientId: ID-STRING
    clientSecret: SECRET-STRING
  gihub:
    clientId: ID-STRING
    clientSecret: SECRET-STRING
  qq:
    clientId: ID-STRING
    clientSecret: SECRET-STRING
  redirectUri: http://127.0.0.1:7070/auth/callback/
  defaultPwd: 123456
  websiteUrl: http://localhost:9000/

aws.waf:
  enabled: false

email:
  test-drive:
    enabled: true
    from: XXX@XX.com
    cc:
      - 1501145746@qq.com
  subscribe:
    enabled: true
    from: XXX@XX.com
    to: 1501145746@qq.com
  publish:
    enabled: true
    from: XXX@XX.com
  contact-us:
    enabled: true
    from: XXX@XX.com
    to: 1501145746@qq.com
  media-contact:
    enabled: true
    from: XXX@XX.com
    to: 1501145746@qq.com
  join-us:
    enabled: true
    from: XXX@XX.com
    to: 1501145746@qq.com
    addr: http://test.baicintl.com/file