options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Create a Cloud Storage bucket for uploads if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil ls -b gs://baic-uploads || gsutil mb -l us-central1 gs://baic-uploads
        gsutil iam ch allUsers:objectViewer gs://baic-uploads

  # Copy uploads directory to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ -d "./uploadPath" ]; then
          gsutil -m cp -r ./uploadPath/* gs://baic-uploads/
          echo "Uploads directory copied to Cloud Storage from ./uploadPath"
        elif [ -d "./beiqi-service-master/beiqi-service-master/uploadPath" ]; then
          gsutil -m cp -r ./beiqi-service-master/beiqi-service-master/uploadPath/* gs://baic-uploads/
          echo "Uploads directory copied to Cloud Storage from ./beiqi-service-master/beiqi-service-master/uploadPath"
        else
          echo "Uploads directory not found, skipping copy"
        fi

  # Update configuration files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        
        # Update the database connection in application-prod.yml for admin
        sed -i 's|jdbc:mysql:///ruoyi?cloudSqlInstance=.*&useSSL=false|jdbc:mysql:///ruoyi?cloudSqlInstance=baic-457613:us-central1:baic-mysql\&socketFactory=com.google.cloud.sql.mysql.SocketFactory\&user=ruoyi\&password=Stellies21!@\&useSSL=false|g' ruoyi-admin/src/main/resources/application-prod.yml
        
        # Update the file upload path to use Cloud Storage for admin
        if grep -q "profile:" ruoyi-admin/src/main/resources/application-prod.yml; then
          sed -i 's|profile:.*|profile: /opt/baic/uploads|g' ruoyi-admin/src/main/resources/application-prod.yml
        else
          echo "ruoyi:" >> ruoyi-admin/src/main/resources/application-prod.yml
          echo "  profile: /opt/baic/uploads" >> ruoyi-admin/src/main/resources/application-prod.yml
        fi
        
        if grep -q "local-storage-path:" ruoyi-admin/src/main/resources/application-prod.yml; then
          sed -i 's|local-storage-path:.*|local-storage-path: /opt/baic/uploads|g' ruoyi-admin/src/main/resources/application-prod.yml
        else
          echo "ufo:" >> ruoyi-admin/src/main/resources/application-prod.yml
          echo "  local-storage-path: /opt/baic/uploads" >> ruoyi-admin/src/main/resources/application-prod.yml
        fi
        
        # Update the database connection in application-prod.yml for web
        sed -i 's|jdbc:mysql:///ruoyi?cloudSqlInstance=.*&useSSL=false|jdbc:mysql:///ruoyi?cloudSqlInstance=baic-457613:us-central1:baic-mysql\&socketFactory=com.google.cloud.sql.mysql.SocketFactory\&user=ruoyi\&password=Stellies21!@\&useSSL=false|g' ruoyi-web/src/main/resources/application-prod.yml
        
        # Update the file upload path to use Cloud Storage for web
        if grep -q "profile:" ruoyi-web/src/main/resources/application-prod.yml; then
          sed -i 's|profile:.*|profile: /opt/baic/uploads|g' ruoyi-web/src/main/resources/application-prod.yml
        else
          echo "ruoyi:" >> ruoyi-web/src/main/resources/application-prod.yml
          echo "  profile: /opt/baic/uploads" >> ruoyi-web/src/main/resources/application-prod.yml
        fi
        
        if grep -q "local-storage-path:" ruoyi-web/src/main/resources/application-prod.yml; then
          sed -i 's|local-storage-path:.*|local-storage-path: /opt/baic/uploads|g' ruoyi-web/src/main/resources/application-prod.yml
        else
          echo "ufo:" >> ruoyi-web/src/main/resources/application-prod.yml
          echo "  local-storage-path: /opt/baic/uploads" >> ruoyi-web/src/main/resources/application-prod.yml
        fi

  # Build the Java projects with Maven
  - name: 'maven:3.8-openjdk-8'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        # Build both modules
        mvn clean package -DskipTests

  # Make the deployment script executable and set up SSH
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        chmod +x vm-deploy.sh
        
        # Use absolute paths for SSH keys
        SSH_DIR="/root/.ssh"
        SSH_KEY="${SSH_DIR}/google_compute_engine"
        SSH_KEY_PUB="${SSH_KEY}.pub"
        
        # Ensure SSH directory exists
        mkdir -p ${SSH_DIR}
        
        # Generate SSH key
        echo "Generating SSH key..."
        ssh-keygen -t rsa -f ${SSH_KEY} -N "" -q
        
        # Display the key for debugging
        echo "SSH key generated:"
        cat ${SSH_KEY_PUB}
        
        # Create VM if it doesn't exist - using hardcoded values to avoid substitution issues
        if ! gcloud compute instances describe baic-backend-vm --zone=us-central1-a &>/dev/null; then
          echo "Creating VM baic-backend-vm..."
          gcloud compute instances create baic-backend-vm \
            --zone=us-central1-a \
            --machine-type=e2-standard-2 \
            --boot-disk-size=20GB \
            --image-family=debian-11 \
            --image-project=debian-cloud \
            --tags=http-server,https-server
        fi
        
        # Add the key to the VM's metadata directly - using hardcoded values
        echo "Adding SSH key to VM metadata..."
        gcloud compute instances add-metadata baic-backend-vm --zone=us-central1-a --metadata="ssh-keys=$(whoami):$(cat ${SSH_KEY_PUB})"
        
        # Configure SSH to not check host keys
        echo "Configuring SSH..."
        mkdir -p ${SSH_DIR}
        echo "Host *" > ${SSH_DIR}/config
        echo "  StrictHostKeyChecking no" >> ${SSH_DIR}/config
        echo "  UserKnownHostsFile /dev/null" >> ${SSH_DIR}/config
        chmod 600 ${SSH_DIR}/config
        
  # Deploy to VM with increased timeout
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Wait for SSH key propagation
        echo "Waiting for SSH key propagation..."
        sleep 30
        
        # Run deployment script
        ./vm-deploy.sh
    timeout: 1800s  # 30 minutes

timeout: 7200s  # 2 hours
