options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Create a Cloud Storage bucket for uploads if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil ls -b gs://baic-uploads || gsutil mb -l us-central1 gs://baic-uploads
        gsutil iam ch allUsers:objectViewer gs://baic-uploads

  # Copy uploads directory to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ -d "./uploadPath" ]; then
          gsutil -m cp -r ./uploadPath/* gs://baic-uploads/
          echo "Uploads directory copied to Cloud Storage from ./uploadPath"
        elif [ -d "./beiqi-service-master/beiqi-service-master/uploadPath" ]; then
          gsutil -m cp -r ./beiqi-service-master/beiqi-service-master/uploadPath/* gs://baic-uploads/
          echo "Uploads directory copied to Cloud Storage from ./beiqi-service-master/beiqi-service-master/uploadPath"
        else
          echo "Uploads directory not found, skipping copy"
        fi

  # Build and deploy GeoIP service to Cloud Run
  # First, update the app.js file to use the PORT environment variable
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-geoip/beiqi-geoip
        # Update the port to use the PORT environment variable
        sed -i 's/const port = 3000;/const port = process.env.PORT || 3000;  \/\/ Use PORT environment variable for Cloud Run or default to 3000 for local development/g' app.js
        
  # Build and deploy the updated GeoIP service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/beiqi-geoip', './beiqi-geoip/beiqi-geoip']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/beiqi-geoip']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'beiqi-geoip', '--image', 'gcr.io/$PROJECT_ID/beiqi-geoip', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

  # Get the backend VM IP address
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-ip'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Get the external IP of the backend VM
        BACKEND_IP=$(gcloud compute instances describe baic-backend-vm --zone=us-central1-a --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        if [ -z "$BACKEND_IP" ]; then
          echo "Error: Could not get the external IP of the backend VM."
          exit 1
        fi
        echo "Backend VM IP: $BACKEND_IP"
        # Save the IP to a file for later use
        echo "$BACKEND_IP" > /workspace/backend_ip.txt

  # Deploy Frontend to App Engine
  - name: 'node:20'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-home-master/beiqi-home-master
        # Update the nuxt.config.js file with the correct backend VM IP address
        BACKEND_IP=$(cat /workspace/backend_ip.txt)
        echo "Updating nuxt.config.js with backend IP: $BACKEND_IP"
        sed -i "s|target: 'http://[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+:8080'|target: 'http://$BACKEND_IP:8080'|g" nuxt.config.js
        
        # Fix API calls in the frontend code
        echo "Fixing API calls in the frontend..."
        API_FILES=$(find api/apiList -type f -name "*.js")
        for file in $API_FILES; do
          echo "Updating $file..."
          # Replace URLs without prefix with /home-api prefix
          sed -i 's|url: "/|url: "/home-api/|g' "$file"
          # Ensure the URL doesn't have double prefixes
          sed -i 's|url: "/home-api/home-api/|url: "/home-api/|g' "$file"
        done
        
        # Create index.scss if it doesn't exist
        if [ ! -f "assets/scss/index.scss" ]; then
          echo "// Import all SCSS files" > assets/scss/index.scss
          echo "@import 'variables';" >> assets/scss/index.scss
          echo "@import 'mixins';" >> assets/scss/index.scss
          echo "@import 'base';" >> assets/scss/index.scss
          echo "@import 'layout';" >> assets/scss/index.scss
          echo "@import 'global';" >> assets/scss/index.scss
          echo "@import 'main';" >> assets/scss/index.scss
          echo "@import 'element-variables';" >> assets/scss/index.scss
          echo "@import 'fonts';" >> assets/scss/index.scss
        fi
        # Install dependencies including the newly added ones
        npm install
        npm install --save @nuxtjs/composition-api@0.33.1
        npm install --save file-loader
        npm install --save @intlify/vue-i18n-loader@1.1.0
        npm run build
        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-home-master/beiqi-home-master
        gcloud app deploy app.yaml --quiet

  # Deploy Backend Admin to App Engine
  # First, update configuration files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        # Update the database connection in application-prod.yml
        sed -i 's|jdbc:mysql:///ruoyi?cloudSqlInstance=.*&useSSL=false|jdbc:mysql:///ruoyi?cloudSqlInstance=baic-457613:us-central1:baic-mysql\&socketFactory=com.google.cloud.sql.mysql.SocketFactory\&user=ruoyi\&password=Stellies21!@\&useSSL=false|g' ruoyi-admin/src/main/resources/application-prod.yml
        
        # Update the file upload path to use Cloud Storage
        if grep -q "profile:" ruoyi-admin/src/main/resources/application-prod.yml; then
          sed -i 's|profile:.*|profile: /uploads|g' ruoyi-admin/src/main/resources/application-prod.yml
        else
          echo "ruoyi:" >> ruoyi-admin/src/main/resources/application-prod.yml
          echo "  profile: /uploads" >> ruoyi-admin/src/main/resources/application-prod.yml
        fi
        
        if grep -q "local-storage-path:" ruoyi-admin/src/main/resources/application-prod.yml; then
          sed -i 's|local-storage-path:.*|local-storage-path: /uploads|g' ruoyi-admin/src/main/resources/application-prod.yml
        else
          echo "ufo:" >> ruoyi-admin/src/main/resources/application-prod.yml
          echo "  local-storage-path: /uploads" >> ruoyi-admin/src/main/resources/application-prod.yml
        fi
  
  # Build the Java project with Maven
  - name: 'maven:3.8-openjdk-8'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        # Build the project from the root directory to ensure parent POM is found
        mvn clean package -DskipTests
  
  # Deploy the built application
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master/ruoyi-admin
        gcloud app deploy app.yaml --quiet

  # Deploy Backend Web to App Engine
  # First, update configuration files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        # Update the database connection in application-prod.yml
        sed -i 's|jdbc:mysql:///ruoyi?cloudSqlInstance=.*&useSSL=false|jdbc:mysql:///ruoyi?cloudSqlInstance=baic-457613:us-central1:baic-mysql\&socketFactory=com.google.cloud.sql.mysql.SocketFactory\&user=ruoyi\&password=Stellies21!@\&useSSL=false|g' ruoyi-web/src/main/resources/application-prod.yml
        
        # Update the file upload path to use Cloud Storage
        if grep -q "profile:" ruoyi-web/src/main/resources/application-prod.yml; then
          sed -i 's|profile:.*|profile: /uploads|g' ruoyi-web/src/main/resources/application-prod.yml
        else
          echo "ruoyi:" >> ruoyi-web/src/main/resources/application-prod.yml
          echo "  profile: /uploads" >> ruoyi-web/src/main/resources/application-prod.yml
        fi
        
        if grep -q "local-storage-path:" ruoyi-web/src/main/resources/application-prod.yml; then
          sed -i 's|local-storage-path:.*|local-storage-path: /uploads|g' ruoyi-web/src/main/resources/application-prod.yml
        else
          echo "ufo:" >> ruoyi-web/src/main/resources/application-prod.yml
          echo "  local-storage-path: /uploads" >> ruoyi-web/src/main/resources/application-prod.yml
        fi
  
  # Deploy the built application (already built in the previous Maven step)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master/ruoyi-web
        gcloud app deploy app.yaml --quiet

  # Deploy Admin Panel to App Engine
  - name: 'node:20'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-web-master/beiqi-web-master
        npm install
        npm run build:prod
        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-web-master/beiqi-web-master
        gcloud app deploy app.yaml --quiet

images:
  - 'gcr.io/$PROJECT_ID/beiqi-geoip'

timeout: 7200s
