options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Create a Cloud Storage bucket for uploads if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil ls -b gs://baic-uploads || gsutil mb -l us-central1 gs://baic-uploads
        gsutil iam ch allUsers:objectViewer gs://baic-uploads

  # Copy configuration scripts
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cp update-nuxt-config.sh beiqi-home-master/beiqi-home-master/
        cp update-plugins.sh beiqi-home-master/beiqi-home-master/
        chmod +x beiqi-home-master/beiqi-home-master/update-nuxt-config.sh
        chmod +x beiqi-home-master/beiqi-home-master/update-plugins.sh

  # Deploy Frontend to App Engine
  - name: 'node:20'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-home-master/beiqi-home-master
        
        # Create index.scss if it doesn't exist
        if [ ! -f "assets/scss/index.scss" ]; then
          echo "// Import all SCSS files" > assets/scss/index.scss
          echo "@import 'variables';" >> assets/scss/index.scss
          echo "@import 'mixins';" >> assets/scss/index.scss
          echo "@import 'base';" >> assets/scss/index.scss
          echo "@import 'layout';" >> assets/scss/index.scss
          echo "@import 'global';" >> assets/scss/index.scss
          echo "@import 'main';" >> assets/scss/index.scss
          echo "@import 'element-variables';" >> assets/scss/index.scss
          echo "@import 'fonts';" >> assets/scss/index.scss
        fi
        
        # Run the scripts to update the configuration
        ./update-plugins.sh
        ./update-nuxt-config.sh
        
        # Install dependencies including the newly added ones
        npm install
        npm install --save @nuxtjs/composition-api@0.33.1
        npm install --save file-loader
        npm install --save @intlify/vue-i18n-loader@1.1.0
        npm run build
        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-home-master/beiqi-home-master
        gcloud app deploy app.yaml --quiet

timeout: 1800s
