options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Create a Cloud Storage bucket for uploads if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil ls -b gs://baic-uploads || gsutil mb -l us-central1 gs://baic-uploads
        gsutil iam ch allUsers:objectViewer gs://baic-uploads

  # Deploy Admin Panel to App Engine
  - name: 'node:20'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-web-master/beiqi-web-master
        
        # Update the .env.production file to point to the VM IP
        echo "# just a flag" > .env.production
        echo "ENV = 'production'" >> .env.production
        echo "" >> .env.production
        echo "# base api" >> .env.production
        echo "VUE_APP_BASE_API = 'http://34.42.200.5:8080/api'" >> .env.production
        
        npm install
        npm run build:prod
        
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-web-master/beiqi-web-master
        gcloud app deploy app.yaml --quiet

timeout: 1800s
