options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Create a Cloud Storage bucket for uploads if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil ls -b gs://baic-uploads || gsutil mb -l us-central1 gs://baic-uploads
        gsutil iam ch allUsers:objectViewer gs://baic-uploads

  # Copy uploads directory to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ -d "./uploadPath" ]; then
          gsutil -m cp -r ./uploadPath/* gs://baic-uploads/
          echo "Uploads directory copied to Cloud Storage from ./uploadPath"
        elif [ -d "./beiqi-service-master/beiqi-service-master/uploadPath" ]; then
          gsutil -m cp -r ./beiqi-service-master/beiqi-service-master/uploadPath/* gs://baic-uploads/
          echo "Uploads directory copied to Cloud Storage from ./beiqi-service-master/beiqi-service-master/uploadPath"
        else
          echo "Uploads directory not found, skipping copy"
        fi

  # Deploy Backend Web to App Engine
  # First, update configuration files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        # Update the database connection in application-prod.yml to use direct connection
        sed -i 's|jdbc:mysql:///ruoyi?cloudSqlInstance=.*&useSSL=false|jdbc:mysql://34.69.17.6:3306/ruoyi?useUnicode=true\&characterEncoding=utf8\&zeroDateTimeBehavior=convertToNull\&useSSL=false\&serverTimezone=GMT%2B8|g' ruoyi-web/src/main/resources/application-prod.yml
        
        # Update the file upload path to use Cloud Storage
        if grep -q "profile:" ruoyi-web/src/main/resources/application-prod.yml; then
          sed -i 's|profile:.*|profile: /uploads|g' ruoyi-web/src/main/resources/application-prod.yml
        else
          echo "ruoyi:" >> ruoyi-web/src/main/resources/application-prod.yml
          echo "  profile: /uploads" >> ruoyi-web/src/main/resources/application-prod.yml
        fi
        
        if grep -q "local-storage-path:" ruoyi-web/src/main/resources/application-prod.yml; then
          sed -i 's|local-storage-path:.*|local-storage-path: /uploads|g' ruoyi-web/src/main/resources/application-prod.yml
        else
          echo "ufo:" >> ruoyi-web/src/main/resources/application-prod.yml
          echo "  local-storage-path: /uploads" >> ruoyi-web/src/main/resources/application-prod.yml
        fi
  
  # Build the Java project with Maven
  - name: 'maven:3.8-openjdk-8'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master
        # Build only the web module and its dependencies
        mvn clean package -DskipTests -pl ruoyi-web -am
  
  # Deploy the built application to App Engine Flexible
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd beiqi-service-master/beiqi-service-master/ruoyi-web
        gcloud app deploy app.yaml --quiet --verbosity=debug

timeout: 7200s  # 2 hours
