runtime: java17
instance_class: F2

automatic_scaling:
  max_instances: 20

env_variables:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql:///ruoyi?cloudSqlInstance=baic-457613:us-central1:baic-mysql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=ruoyi&password=Stellies21!@&useSSL=false
  SERVER_PORT: 8080
