runtime: java11
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql:///ruoyi?cloudSqlInstance=baic-457613:us-central1:baic-mysql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=ruoyi&password=Stellies21!@&useSSL=false
  SERVER_PORT: 8080
