<template>
  <div class="back_top" @click="handleTop" v-show="showTop">
  <img src="~/assets/image/vehicleModel/up.png" alt="" class="up_icon">
<!--    <div class="view_more">view more</div>-->
  </div>
</template>

<script>
export default {
  data() {
    return {
        showTop:false
    }
  },
  mounted: function () {
    window.addEventListener('scroll', this.handleScroll);
  },
  methods: {
    handleScroll() {
      const scrollTop = this.getScroll().top;
      // console.log(scrollTop)
      if(scrollTop>0){

        if(scrollTop> window.screen.height / 2){
          this.showTop = true
        }else{
          this.showTop = false
        }
      }
    },
    getScroll() {
      return {
        left: window.pageXOffset || document.documentElement.scrollLeft || document.body.scrollLeft || 0,
        top: window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0
      };
    },
    handleTop() {
        window.scrollTo({
          top: 0,
          behavior: "smooth"
      });
    }
  },
  beforeDestroy(){
        window.removeEventListener('scroll', this.handleScroll)
    }
}
</script>
<style  scoped lang="scss">
.back_top {
  position: fixed;
  display: flex;
  justify-content: center;
  align-items: center;
  right: 20px;
  bottom: 80px;
  background-color: rgba(255 ,255,255,0.4);
  width: 60px;
  height: 60px;
  border-radius: 50%;
  cursor: pointer;
  z-index: 99;
  box-shadow: 5px 5px 20px 5px rgba(0, 0, 0, 0.3);

    .up_icon{
        width: 50%;
        -webkit-animation: pulsate-fwd 0.5s ease-in-out infinite both;
	        animation: pulsate-fwd 0.5s ease-in-out infinite both;
    }

    .view_more{
      left: 0;
      position: absolute;
      bottom: -24px;
      color: rgba(121, 121, 121, );
      white-space: pre;
      word-spacing: 2px;
      opacity: 0;
      transition: all 0.4s;
    }
    &:hover{
      .view_more{
        opacity: 1;
      }
    }

}
/* ----------------------------------------------
 * Generated by Animista on 2023-8-29 11:51:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-fwd
 * ----------------------------------------
 */
 @-webkit-keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.1);
            transform: scale(1.1);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.1);
            transform: scale(1.1);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

</style>
